[network]
portOffset = 1000

[cluster]
nodeId = 1
partitionsCount = 1
replicationFactor = 2
clusterSize = 2

initialContactPoints = [
  "localhost:26502",
  "localhost:36502"
]

[[exporters]]
id = "simple-monitor"
className = "io.zeebe.monitor.SimpleMonitorExporter"
